### ISSUE TITLE
Improve support for todo.txt-vim

### ISSUE THREAD

**Issue by oxysoft** [jaredgorski/SpaceCamp#11]
Hi, really liking these colors, purple and greens are beautiful together. Sadly I cannot use it yet because I use todo.txt a lot and there is a bit of an annoyance at the moment.

![image](https://user-images.githubusercontent.com/3945277/72005744-4f5a1c00-321c-11ea-9533-99e2b0533777.png)

As you can see, the +project tags aren't highlighted. It's fine for priorities A/B/C which are highlighted by todo.txt, but becomes very annoying with priorities after since they are not.

[This](https://github.com/freitass/todo.txt-vim) is the todo.txt plugin I am using.

edit: Same is true for @context tags.

**Comment by jaredgorski** [comment]
Thanks for the heads up @oxysoft! I'm looking at the plugin's syntax definitions and I think these could be easily added. The definitions are here: https://github.com/freitass/todo.txt-vim/blob/master/syntax/todo.vim

I've tried to make [spacecamp.vim](https://github.com/jaredgorski/SpaceCamp/blob/master/colors/spacecamp.vim) and [spacecamp_lite.vim](https://github.com/jaredgorski/SpaceCamp/blob/master/colors/spacecamp_lite.vim) rather easy files to add syntax support to. If you have time, please feel free to add support in a way that makes you most happy.. and, if you do, send a PR. Otherwise, I may be delayed in adding support for the time being because of other responsibilities.

Is this something you'd like to contribute, or would you prefer to wait until I implement this?

**Comment by oxysoft** [comment]
I'm still fairly new to Vim and have never dealt with the syntax highlighting configuration, seems pretty easy though and it could be a nice introduction. I'll give it a shot maybe tonight or later this weekend!

**Comment by jaredgorski** [comment]
Please do - it's fun and I welcome contributors. Let me know if you end up having questions; happy to help via messages or Skype if needed, particularly on Saturday. Cheers!
